### ISSUE TITLE
Bach: Remove `Series.sorted_ascending` and `Series.index_sorting` properties and use `Series.order_by` instead

### ISSUE THREAD

**Issue by KathiaBarahona** [objectiv/objectiv-analytics#1021]
https://github.com/objectiv/objectiv-analytics/pull/995 adds `order_by` property to `Series`, works similar as in `DataFrame`. Let's now remove the old sorting behavior from `Series`.

**Comment by thijs-obj** [comment]
Related issue: https://github.com/objectiv/objectiv-analytics/issues/396

**Comment by KathiaBarahona** [comment]
Done in https://github.com/objectiv/objectiv-analytics/pull/1037
