### ISSUE TITLE
Bach - Json - Athene - support comparison with string too

### ISSUE THREAD

**Issue by thijs-obj** [objectiv/objectiv-analytics#1142]
**Issues:**`SeriesJson` allows comparisons with other `SeriesJson` objects and `SeriesString` objects, except when running against Athena. Then only comparison between `SeriesJson` and another `SeriesJson` is allowed. See https://github.com/objectiv/objectiv-analytics/pull/1138/files#r942775258

**Tasks:**
* Add tests
* Make comparison between SeriesJson and SeriesString work on Athena.

**Consideration:** An alternative could be to NOT allow comparisons between string and json on other databases. Might make more sense

**Comment by jansentom** [comment]
Fixed by #1153
