### ISSUE TITLE
Modelhub: BQ: deduplicate before all other taxonomy operations

### ISSUE THREAD

**Issue by jansentom** [objectiv/objectiv-analytics#1170]
In order to speed-up the dedup process, we can do this directly after the date filter, and before all other operations on the data, so we have to carry as little columns as possible.

**Comment by KathiaBarahona** [comment]
Seems this was already done https://github.com/objectiv/objectiv-analytics/blob/66dc7b7981b92f01652e77d38c3d11a6ab761e29/modelhub/modelhub/pipelines/extracted_contexts.py#L186-L187
