### ISSUE TITLE
Tracker SDKs anonymous mode

### ISSUE THREAD

**Issue by sdirosa** [objectiv/objectiv-analytics#1239]
New state for Core Tracker to:
- switch to a different endpoint when enabled
- generate SessionContext based on objectiv.clientSessionId global when in anonymous mode

**Comment by ivarpruijn** [comment]
@sdirosa Now fixed?

**Comment by sdirosa** [comment]
@ivarpruijn Yes, but not live yet. It's part of v0.0.26.

**Comment by ivarpruijn** [comment]
Live now, shall we close @sdirosa ?
