### ISSUE TITLE
Bach - support arbitrary column names in database_create_table()

### ISSUE THREAD

**Issue by thijs-obj** [objectiv/objectiv-analytics#1317]
Follow up issue of https://github.com/objectiv/objectiv-analytics/issues/1209

See this TODO: <add link>

tasks:
* If the DataFrame has columns with names that we normally encode, but are valid. Then make sure we use the original column names in the created table. Typical: upper case characters, we lower case them.
* add tests
* make sure that the usage in `DataFrame.get_sample()` is tested too

**Comment by ivarpruijn** [comment]
Is this issue resolved @thijs-obj ?

**Comment by thijs-obj** [comment]
Yes
