### ISSUE TITLE
Bug Report:  Min and Max failing when DataFrame has boolean series

### ISSUE THREAD

**Issue by KathiaBarahona** [objectiv/objectiv-analytics#430]
Currently bach is allowing `min` and `max` aggregations for boolean series, the problem is when executing the sql, since this is functions are not allowed for boolean columns.

**Comment by thijs-obj** [comment]
Make sure to also fix this TODO when that is still relevant: https://github.com/objectiv/objectiv-analytics/pull/374/files#diff-d4893a7bb88c9023e71f83191c81d74803743613b06993bc32baef020420963eR24

**Comment by thijs-obj** [comment]
done, see linked PRs
