### ISSUE TITLE
Optimize SQL generation of `quantile()`

### ISSUE THREAD

**Issue by thijs-obj** [objectiv/objectiv-analytics#488]
series.quantile() generates sql with: 
1) unneeded materializations
2) unneeded group_bys
3) unneeded limits

Some of these points apply to our generated sql code in general. However I specifically noticed this while looking at the sql generated by `qcut()`. It was hard to review the sql code because of the sheer amount of it.

`dataframe.quantile()` is similar.

Of course we should balance generated code quality with python code quality. But it seems worth it to have a look at this.

**Sort of an example**
The generated sql looks something like this:
```sql
with "data" as (
    select * from "base_node"
), "x" as (
    select percentile_cont(0.25) within group (order by "a") as "a", 0.25 as "q"
    from "data"
    group by ()
    limit all
), "y" as (
    select percentile_cont(0.3) within group (order by "a") as "a", 0.3 as "q"
    from "data"
    group by ()
    limit all
), "z" as (
    select percentile_cont(0.7) within group (order by "a") as "a", 0.7 as "q"
    from "data"
    group by ()
    limit all
),
select "q", "a" as "a_a_a_a" from "x"
    union all
select "q", "a" as "a_a_a_a" from "y"
    union all
select "q", "a" as "a_a_a_a" from "z"
```

We could just generate something like:
```sql
with "data" as (
    select * from "base_node"
)
    select percentile_cont(0.25) within group (order by "a") as "a", 0.25 as "q"
    from "data"
union all
    select percentile_cont(0.3) within group (order by "a") as "a", 0.3 as "q"
    from "data"
union all
    select percentile_cont(0.7) within group (order by "a") as "a", 0.7 as "q"
    from "data"
```

**Comment by KathiaBarahona** [comment]
Already solved in https://github.com/objectiv/objectiv-analytics/pull/678
