### ISSUE TITLE
BQ: `DataFrame` loses `order_by` property after `groupby`

### ISSUE THREAD

**Issue by KathiaBarahona** [objectiv/objectiv-analytics#690]
**Issue**: When trying to apply a window function to a `DataFrame`, it seems that the `DataFrame` returned after calling `df.groupby()` loses the column sorting due to materialization. In these cases, functions such as `drop_duplicates` are failing, since `first_value` expects always an `order by`.

**Comment by thijs-obj** [comment]
I think this is mainly a documentation bug. Additionally we might think about improving this behaviour.

The documentation for `DataFrame.sort_values()` says:
```
        The sorting will remain in the returned DataFrame as long as no operations are performed on that
        frame that materially change the selected data. Operations that materially change the selected data
        are for example :py:meth:`groupby`, :py:meth:`merge`, :py:meth:`materialize`, and filtering out rows.
        Adding or removing a column does not materially change the selected data.
```

However, `DataFrame.sort_index()` doesn't have that statement, so that is a **bug** and we should definitely add the documentation there!

**Comment by KathiaBarahona** [comment]
The thing is that it's working for Postgres and not for BigQuery, so when doing:
`df.sort_values(by='x').groupby('x').window(...)` won't yield the same state for each engine.

**Comment by KathiaBarahona** [comment]
> The thing is that it's working for Postgres and not for BigQuery, so when doing: `df.sort_values(by='x').groupby('x').window(...)` won't yield the same state for each engine.

No longer an issue after #938
