### ISSUE TITLE
Bug Report: docker-compose objectiv backend points to private image repository that results in "unauthorized" error whilst following getting-started guide

### ISSUE THREAD

**Issue by peterpeerdeman** [objectiv/objectiv-analytics#746]
**Describe the bug**
hi! i was toying around trying to get objectiv getting started running on my raspberry pi. when using the docker-compose file I got a message that I was not authorized to receive the latest backend image from  eu.gcr.io/objectiv-production/backend:latest . I then built my own docker image using the sources and was able to continue the guide, but maybe this problem will throw some people off trying to get the getting-started guide to run. the original error was as follows below.

perhaps the third line in the docker-compose.yml has pointed me to the wrong image repository? it says:

https://github.com/objectiv/objectiv-analytics/blob/dd730b33376797dde53fd5a291fbc78559e3685e/docker-compose.yaml#L3

**Steps To Reproduce**
1. checkout sourcecode
2. copy the section for the backend collector into my servers docker-compose file
3. replace OBJECTIV_CONTAINER_URL with the repository specified in comment line 4 (eu.gcr.io/objectiv-production)
4. docker-compose up -d

**Expected behavior**
All images run without problem

**Screenshots or Logs**
```
Pulling objectiv_collector (eu.gcr.io/objectiv-production/backend:latest)...
ERROR: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

**Environment (please complete the following information where relevant):**
 - raspberry pi 64bit (arm64)

**Comment by borft** [comment]
I did some investigation, and spoke with @peterpeerdeman directly. It seems there are some old and outdated comments in the `docker-compose.yaml` file, that cause some confusion.

I've created https://github.com/objectiv/objectiv-analytics/pull/747 to address those.

In short, there is no need to set or replace any environmental variables in the `docker-compose.yaml` file, to run the demo stack.

**Comment by peterpeerdeman** [comment]
Thank you for the super speedy reply. Marked as resolved 👍
