### ISSUE TITLE
Collector: Support requiresContext for Contexts

### ISSUE THREAD

**Issue by sdirosa** [objectiv/objectiv-analytics#801]
The "requiresContext" attribute is currently not supported for Context schema.

For Events, the "requiresContext" attribute is a list of context names. The validation checks the presence of each of them in either the Location Stack or Global Contexts and, if any is missing, the Event is rejected and stored in the NOK table.

We want to have same exact attribute available also for Contexts. This will allow us to Specify obligatory Contexts for Location Stacks.

In particular we plan to add `RootLocationContext` and `PathContext` to the list of required contexts of `AbstractLocationContext`. 

Effectively this will validate the integrity of Location Stacks and ensure Interactive Events will always carry RootLocation and Path Contexts.

**Comment by borft** [comment]
should be fixed by https://github.com/objectiv/objectiv-analytics/pull/824

**Comment by sdirosa** [comment]
Just finished testing this up. All works as expected 👍🏼
