### ISSUE TITLE
Bach BQ: fix date and timestamp calculations

### ISSUE THREAD

**Issue by thijs-obj** [objectiv/objectiv-analytics#807]
not all tests for date and timestamps work. Some combinations don't work on BigQuery. Fix those, and make sure all date/timestamp/time/timedelta tests work on BigQuery

**Comment by thijs-obj** [comment]
One test left that has not been made to work with BigQuery yet: `tests.functional.bach.test_series_date.test_date_arithmetic`

**Comment by KathiaBarahona** [comment]
Seems this test is already supported https://github.com/objectiv/objectiv-analytics/pull/1175/files#diff-cb57d8808e90eef52722d2c4360afd069485761d8c407ec980e2b26ce8cbfbde
