### ISSUE TITLE
Bach BQ: make tests related to groupby and window work

### ISSUE THREAD

**Issue by thijs-obj** [objectiv/objectiv-analytics#810]
`test_df_groupby.py` and `test_df_window.py` have a number of tests that don't work with BigQuery.

* Make code fixes to make these tests work
  * improve code
  * raise DatabaseNotSupportedException when appropriate
* Make tests work with BQ

**Comment by KathiaBarahona** [comment]
This issue requires major changes. Let's divide them into subtasks:
1. https://github.com/objectiv/objectiv-analytics/issues/834
2. https://github.com/objectiv/objectiv-analytics/issues/833

Will update later with the rest
