### ISSUE TITLE
[ModelHub] BQ: Non-unique event-ids

### ISSUE THREAD

**Issue by KathiaBarahona** [objectiv/objectiv-analytics#812]
On Postgres the event_id is the primary key, and thus unique. On BigQuery an event_id might appear multiple times. How should we tackle this issue? Grouby-s?

**Comment by thijs-obj** [comment]
This has been fixed in https://github.com/objectiv/objectiv-analytics/pull/939. 

But the tests for it are still an open issue (see https://github.com/objectiv/objectiv-analytics/pull/939#pullrequestreview-1020134494). So let's leave this issue open until that is done

**Comment by thijs-obj** [comment]
@KathiaBarahona We also have tests now, or is that still open?

**Comment by thijs-obj** [comment]
Can you close this issue if that has been tackled?

**Comment by thijs-obj** [comment]
discussed. We have a test for this
