### ISSUE TITLE
[Bach: BQ] Intervals with Nano-precision

### ISSUE THREAD

**Issue by KathiaBarahona** [objectiv/objectiv-analytics#847]
Since modelhub can aggregate session durations by `avg` aggregation function, it is possible to generate something like this:
`0-0 0 00:00:00.123456789`. The main problem is if user tries to convert this into a Timestamp or do `dt.total_seconds`. 
Bach will generate the following expression: `UNIX_MICROS(CAST('1970-01-01' AS TIMESTAMP) + interval_column)` <- this will raise an error when executing a query, since BQ Timestamps support till microseconds precision. I'm still not sure how this can be solved, there's no way to date format an interval, and other idea is extracting each date part from interval and rebuild it (already tried justifying it but does not work)

Here for test:

```sql
with `example_session_duration_nano` as (
  select * from 
    UNNEST([STRUCT<`_index__session_id` INT64, `session_duration` INTERVAL> 
    (2, cast("""P0DT0H0M0S""" as INTERVAL)),
    (4, cast("""P0DT0H0M0.003S""" as INTERVAL)),
    (1, cast("""P0DT0H0M0.001S""" as INTERVAL)),
    (3, cast("""P0DT0H0M0.004S""" as INTERVAL)),
    (5, cast("""P0DT0H0M0S""" as INTERVAL)),
    (6, cast("""P0DT0H0M0S""" as INTERVAL)),
    (7, cast("""P0DT0H0M0S""" as INTERVAL))
  ])
)
select 
avg(`session_duration`) as `average_session_duration`,
CAST('1970-01-01' AS TIMESTAMP) + avg(`session_duration`)  # raises exception: Operation results in TIMESTAMP with nanoseconds precision
from `example_session_duration_nano`

**Comment by KathiaBarahona** [comment]
An alternative solution is rebuilding the interval (it's not really nice and makes the query quite ugly):


```sql
with `example_session_duration_nano` as (
  select * from 
    UNNEST([STRUCT<`_index__session_id` INT64, `session_duration` INTERVAL> 
    (2, cast("""P0DT0H0M0S""" as INTERVAL)),
    (4, cast("""P0DT0H0M0.003S""" as INTERVAL)),
    (1, cast("""P0DT0H0M0.001S""" as INTERVAL)),
    (3, cast("""P0DT0H0M0.004S""" as INTERVAL)),
    (5, cast("""P0DT0H0M0S""" as INTERVAL)),
    (6, cast("""P0DT0H0M0S""" as INTERVAL)),
    (7, cast("""P0DT0H0M0S""" as INTERVAL))
  ])
),
`rebuild_interval` as (
  select
  # build interval by extracting parts and cast the final string back into an interval
  cast(
    extract(year from avg(`session_duration`)) || "-" || extract(month from avg(`session_duration`)) || ' '
    || extract(day from avg(`session_duration`)) || ' '
    || extract(hour from avg(`session_duration`)) || ':' || extract(minute from avg(`session_duration`)) || ':'
    || (

      extract(second from avg(`session_duration`))
      # convert the nanoseconds to microseconds
      + round(extract(nanosecond from avg(`session_duration`)) * 1e-9, 6)
    )
    as interval
  ) as`rebuilt_interval`
  from `example_session_duration_nano`
)
select 
CAST('1970-01-01' AS TIMESTAMP) + `rebuilt_interval`,
UNIX_MICROS(CAST('1970-01-01' AS TIMESTAMP) + `rebuilt_interval`) as `epoch`
from `rebuild_interval`
```

**Comment by jansentom** [comment]
> ```sql
> cast( [snip: loads of extracting] ) as interval
> ```
Alternative to the cast would be to use [`MAKE_INTERVAL`](https://cloud.google.com/bigquery/docs/reference/standard-sql/interval_functions), result would be the same, but maybe slightly less hackish.

**Comment by KathiaBarahona** [comment]
> > ```sql
> > cast( [snip: loads of extracting] ) as interval
> > ```
> 
> Alternative to the cast would be to use [`MAKE_INTERVAL`](https://cloud.google.com/bigquery/docs/reference/standard-sql/interval_functions), result would be the same, but maybe slightly less hackish.

MAKE_INTERVAL doesn't supports microseconds, and all parts must be `int64` :disappointed:  so we lose microsecond precision

**Comment by KathiaBarahona** [comment]
This might help:
```sql
CAST(LEFT(format('%t', avg(`session_duration`)), 18) AS INTERVAL)
```
Problem it truncates the nanoseconds, but should we care?
