### ISSUE TITLE
[Notebooks: BQ] open-taxonomy-how-to.ipynb notebook failing 

### ISSUE THREAD

**Issue by KathiaBarahona** [objectiv/objectiv-analytics#868]
Please check cell number: 26. 
Failing code:
```python
df_sample = df.get_sample(table_name='sample_data', sample_percentage=10, overwrite=True)
```
Raised exception: (google.cloud.bigquery.dbapi.exceptions.DatabaseError) 403 Access Denied: Table objectiv-production:snowplow.sample_data: Permission bigquery.tables.delete denied on table objectiv-production:snowplow.sample_data (or it may not exist).

Location: europe-west4
Job ID: 6aced216-fd5c-48ce-9fb6-07b1578efdee

[SQL: DROP TABLE IF EXISTS `sample_data`]
(Background on this error at: https://sqlalche.me/e/14/4xp6)

**Comment by thijs-obj** [comment]
Tested with latest master: Whole notebook works on BigQuery.

Two manual changes needed to switch from Postgres locally to BigQuery:
1. Change db_url and set credentials
2. Change the `table_name` in cell 26 to a table we can write to, e.g. `'objectiv-production.writable_dataset.sample_data'`


Closing this issue
