### ISSUE TITLE
[Notebooks: BQ] model-hub-demo-notebook.ipynb failing

### ISSUE THREAD

**Issue by KathiaBarahona** [objectiv/objectiv-analytics#871]
Please check cell number: 13. 
Failing code:
```python
modelhub.add_conversion_event(location_stack=df.location_stack.json[{'id': 'Quickstart Guide', '_type': 'LinkContext'}:],
                              event_type='PressEvent',
                              name='quickstart_presses')
df['conversion_events'] = modelhub.map.is_conversion_event(df, 'quickstart_presses')
df.conversion_events.head(10)
```
Raised exception: Slice value must be None or an integer, value: {'id': 'Quickstart Guide', '_type': 'LinkContext'}

**Comment by thijs-obj** [comment]
Tested on latest main: Whole notebook works. Only need to change the call to `get_objectiv_dataframe` to make sure we connect to BigQuery instead of Postgres.

Closing this issue
