### ISSUE TITLE
[Notebooks: BQ] Optimization in cells (Basic Product Analytics)

### ISSUE THREAD

**Issue by KathiaBarahona** [objectiv/objectiv-analytics#882]
Similar to https://github.com/objectiv/objectiv-analytics/issues/881, if some series are not needed for the analysis, let's not include them. For more context:

See suggestion 4 from https://docs.google.com/document/d/1aTopjEqhkWy5GSJcRqi4DEKwSt6h2zVKp6KtMSXsg6s/edit

**Comment by thijs-obj** [comment]
### Other approach that doesn't work
I tried another approach: rewriting the queries a bit. Ideas was to do all the magic of getting the context for each context-type for each event once, and then join the actual data on that (virtual) table to get specific context-types. Gives less (sub)-queries, but the joins are _super_ slow, much slower even than I thought it would be. So that is not a winning approach. Had to cancel the query after a long time.


What I tried (sort of):
```sql
-- .. earlier queries to get the objectiv_session_data
), `data_gc` as (
    select
    `data`.`event_id`,
    `pos`,
    first_value(`ctx`) over (partition by `event_id`, json_value(`ctx`, '$."_type"') order by `pos`) as  `context`,
    json_value(`ctx`, '$."_type"') as `context_type`
    from `objectiv_sessionized_data___5c5453f83d6e9468b0f3cac18b28ba2f` as `data`
    join unnest(json_query_array(`global_contexts`, '$')) as `ctx` with offset `pos`
)

select
    l.`event_id` as `event_id`,
    l.`day` as `day`,
    l.`moment` as `moment`,
    l.`user_id` as `user_id`,
    l.`global_contexts` as `global_contexts`,
    l.`location_stack` as `location_stack`,
    l.`event_type` as `event_type`,
    l.`stack_event_types` as `stack_event_types`,
    l.`session_id` as `session_id`,
    l.`session_hit_number` as `session_hit_number`,
    json_value(`gc_application_context`.`context`, '$."id"') as `root_location`,
    json_value(`gc_http_context`.`context`, '$."referrer"') as `referrer`,
    from `objectiv_sessionized_data___5c5453f83d6e9468b0f3cac18b28ba2f` as `l`
    inner join `data_gc` as `gc_application_context` on l.`event_id` = `gc_application_context`.`event_id` and `gc_application_context`.`context_type` = 'ApplicationContext'
    inner join `data_gc` as `gc_http_context` on l.`event_id` = `gc_http_context`.`event_id` and `gc_http_context`.`context_type` = 'HttpContext'
 -- more
```

**Comment by thijs-obj** [comment]
With the optimizations to modelhub functions and changes to notebooks this works now. So I feel we can close this. Let me know if you feel otherwise.
