### ISSUE TITLE
Add Funnel Analysis

### ISSUE THREAD

**Issue by vard-obj** [objectiv/objectiv-analytics#937]
Funnel Exploration

1. Obtain the sequence of the steps and the conversion event.
    The steps should happen consecutively over the time.

    `step1 -> step2 -> ... -> conversion`

    A step can be both an event triggered by the user or just a user being in a given location at a given time. This can be set with arguments like `event_type` and location stack filtering when running the funnel function. We can use a function similar to `top_product_features_before_conversion` (that internally uses `conversions_in_time` and `conversions_counter`) to get the relevant hits before conversion. 

2. After calculating the data for each step, we do a breakdown of different metrics:
    - number of users/sessions
    - average duration of the sessions
    - top features, etc ...

3. Construct Sankey Diagram using maybe Plotly (https://plotly.com/python/sankey-diagram/).

For later add:
 -  max duration between the steps,
 -  tracking funnel changes over time.

**Comment by ivarpruijn** [comment]
@vard-obj Think this is done?
